export enum Paths {
    LOGIN = '/login',
    LEARN_TO_PLAY = '/learn-to-play',
    HOME = '/',
    RANKING = '/ranking',
    ZOMBIE_CREATE = '/zombie/create',
    ZOMBIE_CREATE_SUCCESS = '/zombie/create/success/:id/:name/:dna',
    ZOMBIE_DETAIL = '/zombie/detail/:id',
    ZOMBIE_FEED = '/zombie/feed/:id',
    ZOMBIE_FEEDING = '/zombie/feeding/:fromDna/:targetDna/:kittyId/:newDna',
    ZOMBIE_ATTACK = '/zombie/attack/:id/:addressEnemie',
    ZOMBIE_ATTACK_VITORY = '/zombie/attack/vitory/:fromId/:targetId/:newDna',
    ZOMBIE_ATTACK_DEFEAT = '/zombie/attack/defeat/:fromId/:targetId',
    ZOMBIE_BATTLE = '/zombie/battle/:id',
    ADMIN_SETTINGS = '/admin/settings',
    MARKETPLACE = '/marketplace',
}
